---
- name: Prepare Ansible bastion
  hosts: all
  become: yes

  tasks:
  - name: Upgrade packages
    ansible.builtin.include_role:
      name: dtoch56.upgrade_packages

  - name: Prepare host
    ansible.builtin.include_role:
      name: dtoch56.prepare_host

  - name: Prepare ssh server
    ansible.builtin.include_role:
      name: dtoch56.ssh
    vars:
      ssh_port: "{{ ansible_bastion_ssh_port }}"
      ssh_ansible_user: "{{ ansible_bastion_user }}"

  - include_tasks: tasks/ufw.yml
    when: ansible_distribution == "Ubuntu"

  - include_tasks: tasks/fail2ban.yml

